<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>patterns</key>
		<array>
			<dict>
				<key>begin</key>
				<string>((@)(interface|protocol))(?!.+;)\s+([A-Za-z_][A-Za-z0-9_]*)\s*((:)(?:\s*)([A-Za-z][A-Za-z0-9]*))?(\s|\n)?</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.objc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.objc</string>
					</dict>
					<key>6</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.entity.other.inherited-class.objc</string>
					</dict>
					<key>7</key>
					<dict>
						<key>name</key>
						<string>entity.other.inherited-class.objc</string>
					</dict>
					<key>8</key>
					<dict>
						<key>name</key>
						<string>meta.divider.objc</string>
					</dict>
					<key>9</key>
					<dict>
						<key>name</key>
						<string>meta.inherited-class.objc</string>
					</dict>
				</dict>
				<key>contentName</key>
				<string>meta.scope.interface.objc</string>
				<key>end</key>
				<string>((@)end)\b</string>
				<key>name</key>
				<string>meta.interface-or-protocol.objc</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#interface_innards</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>((@)(implementation))\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*([A-Za-z][A-Za-z0-9]*))?</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.objc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.objc</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>entity.other.inherited-class.objc</string>
					</dict>
				</dict>
				<key>contentName</key>
				<string>meta.scope.implementation.objc</string>
				<key>end</key>
				<string>((@)end)\b</string>
				<key>name</key>
				<string>meta.implementation.objc</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#implementation_innards</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>applyEndPatternLast</key>
				<true/>
				<key>begin</key>
				<string>(?=@")</string>
				<key>end</key>
				<string>(?=\S)</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>@?"</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.objc</string>
							</dict>
						</dict>
						<key>end</key>
						<string>"</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.objc</string>
							</dict>
						</dict>
						<key>name</key>
						<string>string.quoted.double.objc</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>source.c#string_escaped_char</string>
							</dict>
							<dict>
								<key>match</key>
								<string>(?x)%
    						(\d+\$)?                             # field (argument #)
    						[#0\- +']*                          # flags
    						((-?\d+)|\*(-?\d+\$)?)?              # minimum field width
    						(\.((-?\d+)|\*(-?\d+\$)?)?)?         # precision
    						[@]                                  # conversion type
    					</string>
								<key>name</key>
								<string>constant.other.placeholder.objc</string>
							</dict>
							<dict>
								<key>include</key>
								<string>source.c#string_placeholder</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>\b(id)\s*(?=&lt;)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.objc</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?&lt;=&gt;)</string>
				<key>name</key>
				<string>meta.id-with-protocol.objc</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#protocol_list</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(NS_DURING|NS_HANDLER|NS_ENDHANDLER)\b</string>
				<key>name</key>
				<string>keyword.control.macro.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.keyword.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(try|catch|finally|throw)\b</string>
				<key>name</key>
				<string>keyword.control.exception.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.keyword.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(synchronized)\b</string>
				<key>name</key>
				<string>keyword.control.synchronize.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.keyword.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(required|optional)\b</string>
				<key>name</key>
				<string>keyword.control.protocol-specification.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.keyword.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(defs|encode)\b</string>
				<key>name</key>
				<string>keyword.other.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(class|protocol)\b</string>
				<key>name</key>
				<string>storage.type.objc</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>((@)selector)\s*(\()</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.objc</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
				</dict>
				<key>contentName</key>
				<string>meta.selector.method-name.objc</string>
				<key>end</key>
				<string>(\))</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.type.objc</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.selector.objc</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.separator.arguments.objc</string>
							</dict>
						</dict>
						<key>match</key>
						<string>\b(?:[a-zA-Z_:][\w]*)+</string>
						<key>name</key>
						<string>support.function.any-method.name-of-parameter.objc</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.storage.modifier.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(@)(synchronized|public|package|private|protected)\b</string>
				<key>name</key>
				<string>storage.modifier.objc</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(YES|NO|Nil|nil)\b</string>
				<key>name</key>
				<string>constant.language.objc</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>meta.module.name.objc</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^@import\s+([A-Za-z_][A-Za-z0-9_]*);</string>
				<key>name</key>
				<string>meta.preprocessor.objc.import</string>
			</dict>
			<dict>
				<key>include</key>
				<string>source.objc.platform</string>
			</dict>
			<dict>
				<key>include</key>
				<string>source.c</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#bracketed_content</string>
			</dict>
		</array>
	</dict>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>F85CC716-6B1C-11D9-9A20-000D93589AF6</string>
</dict>
</plist>
